/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedEventsRouteImport } from './routes/embed.events'
import { Route as EmbedEmployeesRouteImport } from './routes/embed.employees'
import { Route as EmbedDonationsRouteImport } from './routes/embed.donations'
import { Route as EmbedAdmissionsRouteImport } from './routes/embed.admissions'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTimetableRouteImport } from './routes/_authenticated/admin.timetable'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated/admin.teachers'
import { Route as AuthenticatedAdminSubjectsRouteImport } from './routes/_authenticated/admin.subjects'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated/admin.students'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminPromotionRouteImport } from './routes/_authenticated/admin.promotion'
import { Route as AuthenticatedAdminParentsRouteImport } from './routes/_authenticated/admin.parents'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminMessagingRouteImport } from './routes/_authenticated/admin.messaging'
import { Route as AuthenticatedAdminLibraryRouteImport } from './routes/_authenticated/admin.library'
import { Route as AuthenticatedAdminInventoryRouteImport } from './routes/_authenticated/admin.inventory'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminHomeworkRouteImport } from './routes/_authenticated/admin.homework'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminFeesRouteImport } from './routes/_authenticated/admin.fees'
import { Route as AuthenticatedAdminExamsRouteImport } from './routes/_authenticated/admin.exams'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin.employees'
import { Route as AuthenticatedAdminDriversRouteImport } from './routes/_authenticated/admin.drivers'
import { Route as AuthenticatedAdminDonationsRouteImport } from './routes/_authenticated/admin.donations'
import { Route as AuthenticatedAdminClassesRouteImport } from './routes/_authenticated/admin.classes'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAttendanceRouteImport } from './routes/_authenticated/admin.attendance'
import { Route as AuthenticatedAdminAdmissionsRouteImport } from './routes/_authenticated/admin.admissions'
import { Route as AuthenticatedAdminSetupRolesRouteImport } from './routes/_authenticated/admin.setup.roles'
import { Route as AuthenticatedAdminSetupPayrollRouteImport } from './routes/_authenticated/admin.setup.payroll'
import { Route as AuthenticatedAdminSetupFeesRouteImport } from './routes/_authenticated/admin.setup.fees'
import { Route as AuthenticatedAdminSetupDepartmentsRouteImport } from './routes/_authenticated/admin.setup.departments'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedEventsRoute = EmbedEventsRouteImport.update({
  id: '/embed/events',
  path: '/embed/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedEmployeesRoute = EmbedEmployeesRouteImport.update({
  id: '/embed/employees',
  path: '/embed/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedDonationsRoute = EmbedDonationsRouteImport.update({
  id: '/embed/donations',
  path: '/embed/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedAdmissionsRoute = EmbedAdmissionsRouteImport.update({
  id: '/embed/admissions',
  path: '/embed/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTimetableRoute =
  AuthenticatedAdminTimetableRouteImport.update({
    id: '/timetable',
    path: '/timetable',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubjectsRoute =
  AuthenticatedAdminSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromotionRoute =
  AuthenticatedAdminPromotionRouteImport.update({
    id: '/promotion',
    path: '/promotion',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParentsRoute =
  AuthenticatedAdminParentsRouteImport.update({
    id: '/parents',
    path: '/parents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMessagingRoute =
  AuthenticatedAdminMessagingRouteImport.update({
    id: '/messaging',
    path: '/messaging',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLibraryRoute =
  AuthenticatedAdminLibraryRouteImport.update({
    id: '/library',
    path: '/library',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInventoryRoute =
  AuthenticatedAdminInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHomeworkRoute =
  AuthenticatedAdminHomeworkRouteImport.update({
    id: '/homework',
    path: '/homework',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeesRoute = AuthenticatedAdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminExamsRoute = AuthenticatedAdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDriversRoute =
  AuthenticatedAdminDriversRouteImport.update({
    id: '/drivers',
    path: '/drivers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDonationsRoute =
  AuthenticatedAdminDonationsRouteImport.update({
    id: '/donations',
    path: '/donations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClassesRoute =
  AuthenticatedAdminClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAttendanceRoute =
  AuthenticatedAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdmissionsRoute =
  AuthenticatedAdminAdmissionsRouteImport.update({
    id: '/admissions',
    path: '/admissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSetupRolesRoute =
  AuthenticatedAdminSetupRolesRouteImport.update({
    id: '/setup/roles',
    path: '/setup/roles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSetupPayrollRoute =
  AuthenticatedAdminSetupPayrollRouteImport.update({
    id: '/setup/payroll',
    path: '/setup/payroll',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSetupFeesRoute =
  AuthenticatedAdminSetupFeesRouteImport.update({
    id: '/setup/fees',
    path: '/setup/fees',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSetupDepartmentsRoute =
  AuthenticatedAdminSetupDepartmentsRouteImport.update({
    id: '/setup/departments',
    path: '/setup/departments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/portal': typeof AuthenticatedPortalRoute
  '/embed/admissions': typeof EmbedAdmissionsRoute
  '/embed/donations': typeof EmbedDonationsRoute
  '/embed/employees': typeof EmbedEmployeesRoute
  '/embed/events': typeof EmbedEventsRoute
  '/admin/admissions': typeof AuthenticatedAdminAdmissionsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/homework': typeof AuthenticatedAdminHomeworkRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/admin/messaging': typeof AuthenticatedAdminMessagingRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/parents': typeof AuthenticatedAdminParentsRoute
  '/admin/promotion': typeof AuthenticatedAdminPromotionRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/admin/timetable': typeof AuthenticatedAdminTimetableRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/setup/departments': typeof AuthenticatedAdminSetupDepartmentsRoute
  '/admin/setup/fees': typeof AuthenticatedAdminSetupFeesRoute
  '/admin/setup/payroll': typeof AuthenticatedAdminSetupPayrollRoute
  '/admin/setup/roles': typeof AuthenticatedAdminSetupRolesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/embed/admissions': typeof EmbedAdmissionsRoute
  '/embed/donations': typeof EmbedDonationsRoute
  '/embed/employees': typeof EmbedEmployeesRoute
  '/embed/events': typeof EmbedEventsRoute
  '/admin/admissions': typeof AuthenticatedAdminAdmissionsRoute
  '/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/events': typeof AuthenticatedAdminEventsRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/homework': typeof AuthenticatedAdminHomeworkRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/admin/messaging': typeof AuthenticatedAdminMessagingRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/parents': typeof AuthenticatedAdminParentsRoute
  '/admin/promotion': typeof AuthenticatedAdminPromotionRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/admin/timetable': typeof AuthenticatedAdminTimetableRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/setup/departments': typeof AuthenticatedAdminSetupDepartmentsRoute
  '/admin/setup/fees': typeof AuthenticatedAdminSetupFeesRoute
  '/admin/setup/payroll': typeof AuthenticatedAdminSetupPayrollRoute
  '/admin/setup/roles': typeof AuthenticatedAdminSetupRolesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/embed/admissions': typeof EmbedAdmissionsRoute
  '/embed/donations': typeof EmbedDonationsRoute
  '/embed/employees': typeof EmbedEmployeesRoute
  '/embed/events': typeof EmbedEventsRoute
  '/_authenticated/admin/admissions': typeof AuthenticatedAdminAdmissionsRoute
  '/_authenticated/admin/attendance': typeof AuthenticatedAdminAttendanceRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/_authenticated/admin/donations': typeof AuthenticatedAdminDonationsRoute
  '/_authenticated/admin/drivers': typeof AuthenticatedAdminDriversRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRoute
  '/_authenticated/admin/exams': typeof AuthenticatedAdminExamsRoute
  '/_authenticated/admin/fees': typeof AuthenticatedAdminFeesRoute
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/homework': typeof AuthenticatedAdminHomeworkRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/inventory': typeof AuthenticatedAdminInventoryRoute
  '/_authenticated/admin/library': typeof AuthenticatedAdminLibraryRoute
  '/_authenticated/admin/messaging': typeof AuthenticatedAdminMessagingRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/parents': typeof AuthenticatedAdminParentsRoute
  '/_authenticated/admin/promotion': typeof AuthenticatedAdminPromotionRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/_authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/_authenticated/admin/timetable': typeof AuthenticatedAdminTimetableRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/setup/departments': typeof AuthenticatedAdminSetupDepartmentsRoute
  '/_authenticated/admin/setup/fees': typeof AuthenticatedAdminSetupFeesRoute
  '/_authenticated/admin/setup/payroll': typeof AuthenticatedAdminSetupPayrollRoute
  '/_authenticated/admin/setup/roles': typeof AuthenticatedAdminSetupRolesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/portal'
    | '/embed/admissions'
    | '/embed/donations'
    | '/embed/employees'
    | '/embed/events'
    | '/admin/admissions'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/classes'
    | '/admin/donations'
    | '/admin/drivers'
    | '/admin/employees'
    | '/admin/events'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/finance'
    | '/admin/homework'
    | '/admin/import'
    | '/admin/inventory'
    | '/admin/library'
    | '/admin/messaging'
    | '/admin/notifications'
    | '/admin/parents'
    | '/admin/promotion'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/admin/users'
    | '/admin/'
    | '/admin/setup/departments'
    | '/admin/setup/fees'
    | '/admin/setup/payroll'
    | '/admin/setup/roles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/embed/admissions'
    | '/embed/donations'
    | '/embed/employees'
    | '/embed/events'
    | '/admin/admissions'
    | '/admin/attendance'
    | '/admin/audit'
    | '/admin/classes'
    | '/admin/donations'
    | '/admin/drivers'
    | '/admin/employees'
    | '/admin/events'
    | '/admin/exams'
    | '/admin/fees'
    | '/admin/finance'
    | '/admin/homework'
    | '/admin/import'
    | '/admin/inventory'
    | '/admin/library'
    | '/admin/messaging'
    | '/admin/notifications'
    | '/admin/parents'
    | '/admin/promotion'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/admin/users'
    | '/admin'
    | '/admin/setup/departments'
    | '/admin/setup/fees'
    | '/admin/setup/payroll'
    | '/admin/setup/roles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/embed/admissions'
    | '/embed/donations'
    | '/embed/employees'
    | '/embed/events'
    | '/_authenticated/admin/admissions'
    | '/_authenticated/admin/attendance'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/classes'
    | '/_authenticated/admin/donations'
    | '/_authenticated/admin/drivers'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/exams'
    | '/_authenticated/admin/fees'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/homework'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/inventory'
    | '/_authenticated/admin/library'
    | '/_authenticated/admin/messaging'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/parents'
    | '/_authenticated/admin/promotion'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/subjects'
    | '/_authenticated/admin/teachers'
    | '/_authenticated/admin/timetable'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/setup/departments'
    | '/_authenticated/admin/setup/fees'
    | '/_authenticated/admin/setup/payroll'
    | '/_authenticated/admin/setup/roles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EmbedAdmissionsRoute: typeof EmbedAdmissionsRoute
  EmbedDonationsRoute: typeof EmbedDonationsRoute
  EmbedEmployeesRoute: typeof EmbedEmployeesRoute
  EmbedEventsRoute: typeof EmbedEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/events': {
      id: '/embed/events'
      path: '/embed/events'
      fullPath: '/embed/events'
      preLoaderRoute: typeof EmbedEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/employees': {
      id: '/embed/employees'
      path: '/embed/employees'
      fullPath: '/embed/employees'
      preLoaderRoute: typeof EmbedEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/donations': {
      id: '/embed/donations'
      path: '/embed/donations'
      fullPath: '/embed/donations'
      preLoaderRoute: typeof EmbedDonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/admissions': {
      id: '/embed/admissions'
      path: '/embed/admissions'
      fullPath: '/embed/admissions'
      preLoaderRoute: typeof EmbedAdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/timetable': {
      id: '/_authenticated/admin/timetable'
      path: '/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AuthenticatedAdminTimetableRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/teachers': {
      id: '/_authenticated/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subjects': {
      id: '/_authenticated/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promotion': {
      id: '/_authenticated/admin/promotion'
      path: '/promotion'
      fullPath: '/admin/promotion'
      preLoaderRoute: typeof AuthenticatedAdminPromotionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parents': {
      id: '/_authenticated/admin/parents'
      path: '/parents'
      fullPath: '/admin/parents'
      preLoaderRoute: typeof AuthenticatedAdminParentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/messaging': {
      id: '/_authenticated/admin/messaging'
      path: '/messaging'
      fullPath: '/admin/messaging'
      preLoaderRoute: typeof AuthenticatedAdminMessagingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/library': {
      id: '/_authenticated/admin/library'
      path: '/library'
      fullPath: '/admin/library'
      preLoaderRoute: typeof AuthenticatedAdminLibraryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inventory': {
      id: '/_authenticated/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AuthenticatedAdminInventoryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/homework': {
      id: '/_authenticated/admin/homework'
      path: '/homework'
      fullPath: '/admin/homework'
      preLoaderRoute: typeof AuthenticatedAdminHomeworkRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/fees': {
      id: '/_authenticated/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AuthenticatedAdminFeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/exams': {
      id: '/_authenticated/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminExamsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/drivers': {
      id: '/_authenticated/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AuthenticatedAdminDriversRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/donations': {
      id: '/_authenticated/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AuthenticatedAdminDonationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/classes': {
      id: '/_authenticated/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AuthenticatedAdminClassesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/attendance': {
      id: '/_authenticated/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AuthenticatedAdminAttendanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admissions': {
      id: '/_authenticated/admin/admissions'
      path: '/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AuthenticatedAdminAdmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/setup/roles': {
      id: '/_authenticated/admin/setup/roles'
      path: '/setup/roles'
      fullPath: '/admin/setup/roles'
      preLoaderRoute: typeof AuthenticatedAdminSetupRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/setup/payroll': {
      id: '/_authenticated/admin/setup/payroll'
      path: '/setup/payroll'
      fullPath: '/admin/setup/payroll'
      preLoaderRoute: typeof AuthenticatedAdminSetupPayrollRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/setup/fees': {
      id: '/_authenticated/admin/setup/fees'
      path: '/setup/fees'
      fullPath: '/admin/setup/fees'
      preLoaderRoute: typeof AuthenticatedAdminSetupFeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/setup/departments': {
      id: '/_authenticated/admin/setup/departments'
      path: '/setup/departments'
      fullPath: '/admin/setup/departments'
      preLoaderRoute: typeof AuthenticatedAdminSetupDepartmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdmissionsRoute: typeof AuthenticatedAdminAdmissionsRoute
  AuthenticatedAdminAttendanceRoute: typeof AuthenticatedAdminAttendanceRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminClassesRoute: typeof AuthenticatedAdminClassesRoute
  AuthenticatedAdminDonationsRoute: typeof AuthenticatedAdminDonationsRoute
  AuthenticatedAdminDriversRoute: typeof AuthenticatedAdminDriversRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRoute
  AuthenticatedAdminExamsRoute: typeof AuthenticatedAdminExamsRoute
  AuthenticatedAdminFeesRoute: typeof AuthenticatedAdminFeesRoute
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminHomeworkRoute: typeof AuthenticatedAdminHomeworkRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminInventoryRoute: typeof AuthenticatedAdminInventoryRoute
  AuthenticatedAdminLibraryRoute: typeof AuthenticatedAdminLibraryRoute
  AuthenticatedAdminMessagingRoute: typeof AuthenticatedAdminMessagingRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminParentsRoute: typeof AuthenticatedAdminParentsRoute
  AuthenticatedAdminPromotionRoute: typeof AuthenticatedAdminPromotionRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminSubjectsRoute: typeof AuthenticatedAdminSubjectsRoute
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
  AuthenticatedAdminTimetableRoute: typeof AuthenticatedAdminTimetableRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminSetupDepartmentsRoute: typeof AuthenticatedAdminSetupDepartmentsRoute
  AuthenticatedAdminSetupFeesRoute: typeof AuthenticatedAdminSetupFeesRoute
  AuthenticatedAdminSetupPayrollRoute: typeof AuthenticatedAdminSetupPayrollRoute
  AuthenticatedAdminSetupRolesRoute: typeof AuthenticatedAdminSetupRolesRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdmissionsRoute: AuthenticatedAdminAdmissionsRoute,
  AuthenticatedAdminAttendanceRoute: AuthenticatedAdminAttendanceRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminClassesRoute: AuthenticatedAdminClassesRoute,
  AuthenticatedAdminDonationsRoute: AuthenticatedAdminDonationsRoute,
  AuthenticatedAdminDriversRoute: AuthenticatedAdminDriversRoute,
  AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRoute,
  AuthenticatedAdminExamsRoute: AuthenticatedAdminExamsRoute,
  AuthenticatedAdminFeesRoute: AuthenticatedAdminFeesRoute,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminHomeworkRoute: AuthenticatedAdminHomeworkRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminInventoryRoute: AuthenticatedAdminInventoryRoute,
  AuthenticatedAdminLibraryRoute: AuthenticatedAdminLibraryRoute,
  AuthenticatedAdminMessagingRoute: AuthenticatedAdminMessagingRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminParentsRoute: AuthenticatedAdminParentsRoute,
  AuthenticatedAdminPromotionRoute: AuthenticatedAdminPromotionRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminSubjectsRoute: AuthenticatedAdminSubjectsRoute,
  AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
  AuthenticatedAdminTimetableRoute: AuthenticatedAdminTimetableRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminSetupDepartmentsRoute:
    AuthenticatedAdminSetupDepartmentsRoute,
  AuthenticatedAdminSetupFeesRoute: AuthenticatedAdminSetupFeesRoute,
  AuthenticatedAdminSetupPayrollRoute: AuthenticatedAdminSetupPayrollRoute,
  AuthenticatedAdminSetupRolesRoute: AuthenticatedAdminSetupRolesRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EmbedAdmissionsRoute: EmbedAdmissionsRoute,
  EmbedDonationsRoute: EmbedDonationsRoute,
  EmbedEmployeesRoute: EmbedEmployeesRoute,
  EmbedEventsRoute: EmbedEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
