GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT USAGE ON SCHEMA public TO service_role;

GRANT ALL ON FUNCTION public.apply_inventory_transaction() TO anon;
GRANT ALL ON FUNCTION public.apply_inventory_transaction() TO authenticated;
GRANT ALL ON FUNCTION public.apply_inventory_transaction() TO service_role;
GRANT ALL ON FUNCTION public.handle_book_issue_change() TO anon;
GRANT ALL ON FUNCTION public.handle_book_issue_change() TO authenticated;
GRANT ALL ON FUNCTION public.handle_book_issue_change() TO service_role;
GRANT ALL ON FUNCTION public.handle_new_user() TO anon;
GRANT ALL ON FUNCTION public.handle_new_user() TO authenticated;
GRANT ALL ON FUNCTION public.handle_new_user() TO service_role;
GRANT ALL ON FUNCTION public.has_role(_user_id uuid, _role public.app_role) TO anon;
GRANT ALL ON FUNCTION public.has_role(_user_id uuid, _role public.app_role) TO authenticated;
GRANT ALL ON FUNCTION public.has_role(_user_id uuid, _role public.app_role) TO service_role;
GRANT ALL ON FUNCTION public.recompute_invoice_totals() TO anon;
GRANT ALL ON FUNCTION public.recompute_invoice_totals() TO authenticated;
GRANT ALL ON FUNCTION public.recompute_invoice_totals() TO service_role;
GRANT ALL ON FUNCTION public.set_updated_at() TO anon;
GRANT ALL ON FUNCTION public.set_updated_at() TO authenticated;
GRANT ALL ON FUNCTION public.set_updated_at() TO service_role;

GRANT ALL ON TABLE public.admission_applications TO anon;
GRANT ALL ON TABLE public.admission_applications TO authenticated;
GRANT ALL ON TABLE public.admission_applications TO service_role;
GRANT ALL ON TABLE public.admission_interviews TO anon;
GRANT ALL ON TABLE public.admission_interviews TO authenticated;
GRANT ALL ON TABLE public.admission_interviews TO service_role;
GRANT ALL ON TABLE public.announcements TO anon;
GRANT ALL ON TABLE public.announcements TO authenticated;
GRANT ALL ON TABLE public.announcements TO service_role;
GRANT ALL ON TABLE public.attendance TO anon;
GRANT ALL ON TABLE public.attendance TO authenticated;
GRANT ALL ON TABLE public.attendance TO service_role;
GRANT ALL ON TABLE public.attendance_deduction_rules TO anon;
GRANT ALL ON TABLE public.attendance_deduction_rules TO authenticated;
GRANT ALL ON TABLE public.attendance_deduction_rules TO service_role;
GRANT ALL ON TABLE public.audit_logs TO anon;
GRANT ALL ON TABLE public.audit_logs TO authenticated;
GRANT ALL ON TABLE public.audit_logs TO service_role;
GRANT ALL ON TABLE public.book_issues TO anon;
GRANT ALL ON TABLE public.book_issues TO authenticated;
GRANT ALL ON TABLE public.book_issues TO service_role;
GRANT ALL ON TABLE public.books TO anon;
GRANT ALL ON TABLE public.books TO authenticated;
GRANT ALL ON TABLE public.books TO service_role;
GRANT ALL ON TABLE public.classes TO anon;
GRANT ALL ON TABLE public.classes TO authenticated;
GRANT ALL ON TABLE public.classes TO service_role;
GRANT ALL ON TABLE public.deduction_components TO anon;
GRANT ALL ON TABLE public.deduction_components TO authenticated;
GRANT ALL ON TABLE public.deduction_components TO service_role;
GRANT ALL ON TABLE public.departments TO anon;
GRANT ALL ON TABLE public.departments TO authenticated;
GRANT ALL ON TABLE public.departments TO service_role;
GRANT ALL ON TABLE public.donations TO anon;
GRANT ALL ON TABLE public.donations TO authenticated;
GRANT ALL ON TABLE public.donations TO service_role;
GRANT ALL ON TABLE public.drivers TO anon;
GRANT ALL ON TABLE public.drivers TO authenticated;
GRANT ALL ON TABLE public.drivers TO service_role;
GRANT ALL ON TABLE public.employment_applications TO anon;
GRANT ALL ON TABLE public.employment_applications TO authenticated;
GRANT ALL ON TABLE public.employment_applications TO service_role;
GRANT ALL ON TABLE public.events TO anon;
GRANT ALL ON TABLE public.events TO authenticated;
GRANT ALL ON TABLE public.events TO service_role;
GRANT ALL ON TABLE public.exam_results TO anon;
GRANT ALL ON TABLE public.exam_results TO authenticated;
GRANT ALL ON TABLE public.exam_results TO service_role;
GRANT ALL ON TABLE public.exams TO anon;
GRANT ALL ON TABLE public.exams TO authenticated;
GRANT ALL ON TABLE public.exams TO service_role;
GRANT ALL ON TABLE public.fee_challans TO anon;
GRANT ALL ON TABLE public.fee_challans TO authenticated;
GRANT ALL ON TABLE public.fee_challans TO service_role;
GRANT ALL ON TABLE public.fee_constituents TO anon;
GRANT ALL ON TABLE public.fee_constituents TO authenticated;
GRANT ALL ON TABLE public.fee_constituents TO service_role;
GRANT ALL ON TABLE public.fee_group_constituents TO anon;
GRANT ALL ON TABLE public.fee_group_constituents TO authenticated;
GRANT ALL ON TABLE public.fee_group_constituents TO service_role;
GRANT ALL ON TABLE public.fee_groups TO anon;
GRANT ALL ON TABLE public.fee_groups TO authenticated;
GRANT ALL ON TABLE public.fee_groups TO service_role;
GRANT ALL ON TABLE public.fee_structures TO anon;
GRANT ALL ON TABLE public.fee_structures TO authenticated;
GRANT ALL ON TABLE public.fee_structures TO service_role;
GRANT ALL ON TABLE public.grading_scales TO anon;
GRANT ALL ON TABLE public.grading_scales TO authenticated;
GRANT ALL ON TABLE public.grading_scales TO service_role;
GRANT ALL ON TABLE public.homework TO anon;
GRANT ALL ON TABLE public.homework TO authenticated;
GRANT ALL ON TABLE public.homework TO service_role;
GRANT ALL ON TABLE public.homework_submissions TO anon;
GRANT ALL ON TABLE public.homework_submissions TO authenticated;
GRANT ALL ON TABLE public.homework_submissions TO service_role;
GRANT ALL ON TABLE public.import_profiles TO anon;
GRANT ALL ON TABLE public.import_profiles TO authenticated;
GRANT ALL ON TABLE public.import_profiles TO service_role;
GRANT ALL ON TABLE public.inventory_categories TO anon;
GRANT ALL ON TABLE public.inventory_categories TO authenticated;
GRANT ALL ON TABLE public.inventory_categories TO service_role;
GRANT ALL ON TABLE public.inventory_items TO anon;
GRANT ALL ON TABLE public.inventory_items TO authenticated;
GRANT ALL ON TABLE public.inventory_items TO service_role;
GRANT ALL ON TABLE public.inventory_transactions TO anon;
GRANT ALL ON TABLE public.inventory_transactions TO authenticated;
GRANT ALL ON TABLE public.inventory_transactions TO service_role;
GRANT ALL ON TABLE public.invoices TO anon;
GRANT ALL ON TABLE public.invoices TO authenticated;
GRANT ALL ON TABLE public.invoices TO service_role;
GRANT ALL ON TABLE public.messages TO anon;
GRANT ALL ON TABLE public.messages TO authenticated;
GRANT ALL ON TABLE public.messages TO service_role;
GRANT ALL ON TABLE public.notifications TO anon;
GRANT ALL ON TABLE public.notifications TO authenticated;
GRANT ALL ON TABLE public.notifications TO service_role;
GRANT ALL ON TABLE public.parent_contacts TO anon;
GRANT ALL ON TABLE public.parent_contacts TO authenticated;
GRANT ALL ON TABLE public.parent_contacts TO service_role;
GRANT ALL ON TABLE public.parents TO anon;
GRANT ALL ON TABLE public.parents TO authenticated;
GRANT ALL ON TABLE public.parents TO service_role;
GRANT ALL ON TABLE public.payments TO anon;
GRANT ALL ON TABLE public.payments TO authenticated;
GRANT ALL ON TABLE public.payments TO service_role;
GRANT ALL ON TABLE public.payroll_item_lines TO anon;
GRANT ALL ON TABLE public.payroll_item_lines TO authenticated;
GRANT ALL ON TABLE public.payroll_item_lines TO service_role;
GRANT ALL ON TABLE public.payroll_items TO anon;
GRANT ALL ON TABLE public.payroll_items TO authenticated;
GRANT ALL ON TABLE public.payroll_items TO service_role;
GRANT ALL ON TABLE public.payroll_run_bonus_lines TO anon;
GRANT ALL ON TABLE public.payroll_run_bonus_lines TO authenticated;
GRANT ALL ON TABLE public.payroll_run_bonus_lines TO service_role;
GRANT ALL ON TABLE public.payroll_runs TO anon;
GRANT ALL ON TABLE public.payroll_runs TO authenticated;
GRANT ALL ON TABLE public.payroll_runs TO service_role;
GRANT ALL ON TABLE public.profiles TO anon;
GRANT ALL ON TABLE public.profiles TO authenticated;
GRANT ALL ON TABLE public.profiles TO service_role;
GRANT ALL ON TABLE public.role_permissions TO anon;
GRANT ALL ON TABLE public.role_permissions TO authenticated;
GRANT ALL ON TABLE public.role_permissions TO service_role;
GRANT ALL ON TABLE public.roles TO anon;
GRANT ALL ON TABLE public.roles TO authenticated;
GRANT ALL ON TABLE public.roles TO service_role;
GRANT ALL ON TABLE public.school_settings TO anon;
GRANT ALL ON TABLE public.school_settings TO authenticated;
GRANT ALL ON TABLE public.school_settings TO service_role;
GRANT ALL ON TABLE public.staff_attendance TO anon;
GRANT ALL ON TABLE public.staff_attendance TO authenticated;
GRANT ALL ON TABLE public.staff_attendance TO service_role;
GRANT ALL ON TABLE public.student_parents TO anon;
GRANT ALL ON TABLE public.student_parents TO authenticated;
GRANT ALL ON TABLE public.student_parents TO service_role;
GRANT ALL ON TABLE public.students TO anon;
GRANT ALL ON TABLE public.students TO authenticated;
GRANT ALL ON TABLE public.students TO service_role;
GRANT ALL ON TABLE public.subjects TO anon;
GRANT ALL ON TABLE public.subjects TO authenticated;
GRANT ALL ON TABLE public.subjects TO service_role;
GRANT ALL ON TABLE public.teachers TO anon;
GRANT ALL ON TABLE public.teachers TO authenticated;
GRANT ALL ON TABLE public.teachers TO service_role;
GRANT ALL ON TABLE public.timetable_slots TO anon;
GRANT ALL ON TABLE public.timetable_slots TO authenticated;
GRANT ALL ON TABLE public.timetable_slots TO service_role;
GRANT ALL ON TABLE public.transport_assignments TO anon;
GRANT ALL ON TABLE public.transport_assignments TO authenticated;
GRANT ALL ON TABLE public.transport_assignments TO service_role;
GRANT ALL ON TABLE public.transport_routes TO anon;
GRANT ALL ON TABLE public.transport_routes TO authenticated;
GRANT ALL ON TABLE public.transport_routes TO service_role;
GRANT ALL ON TABLE public.transport_vehicles TO anon;
GRANT ALL ON TABLE public.transport_vehicles TO authenticated;
GRANT ALL ON TABLE public.transport_vehicles TO service_role;
GRANT ALL ON TABLE public.user_roles TO anon;
GRANT ALL ON TABLE public.user_roles TO authenticated;
GRANT ALL ON TABLE public.user_roles TO service_role;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

INSERT INTO storage.buckets (id, name, public)
VALUES ('payment-proofs', 'payment-proofs', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "proofs upload" ON storage.objects;
CREATE POLICY "proofs upload" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'payment-proofs');

DROP POLICY IF EXISTS "proofs own read" ON storage.objects;
CREATE POLICY "proofs own read" ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id = 'payment-proofs' AND (owner = auth.uid() OR public.has_role(auth.uid(), 'admin')));

DROP POLICY IF EXISTS "proofs admin delete" ON storage.objects;
CREATE POLICY "proofs admin delete" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'payment-proofs' AND public.has_role(auth.uid(), 'admin'));