ALTER TABLE ONLY public.admission_applications ADD CONSTRAINT admission_applications_application_no_key UNIQUE (application_no);
ALTER TABLE ONLY public.admission_applications ADD CONSTRAINT admission_applications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.admission_interviews ADD CONSTRAINT admission_interviews_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.announcements ADD CONSTRAINT announcements_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.attendance ADD CONSTRAINT attendance_class_id_student_id_date_key UNIQUE (class_id, student_id, date);
ALTER TABLE ONLY public.attendance_deduction_rules ADD CONSTRAINT attendance_deduction_rules_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.attendance ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.audit_logs ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.book_issues ADD CONSTRAINT book_issues_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.books ADD CONSTRAINT books_isbn_key UNIQUE (isbn);
ALTER TABLE ONLY public.books ADD CONSTRAINT books_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.classes ADD CONSTRAINT classes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.deduction_components ADD CONSTRAINT deduction_components_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.departments ADD CONSTRAINT departments_name_key UNIQUE (name);
ALTER TABLE ONLY public.departments ADD CONSTRAINT departments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.donations ADD CONSTRAINT donations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.drivers ADD CONSTRAINT drivers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.employment_applications ADD CONSTRAINT employment_applications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.events ADD CONSTRAINT events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.exam_results ADD CONSTRAINT exam_results_exam_id_student_id_key UNIQUE (exam_id, student_id);
ALTER TABLE ONLY public.exam_results ADD CONSTRAINT exam_results_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.exams ADD CONSTRAINT exams_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.fee_challans ADD CONSTRAINT fee_challans_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.fee_challans ADD CONSTRAINT fee_challans_student_id_period_key UNIQUE (student_id, period);
ALTER TABLE ONLY public.fee_constituents ADD CONSTRAINT fee_constituents_name_key UNIQUE (name);
ALTER TABLE ONLY public.fee_constituents ADD CONSTRAINT fee_constituents_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.fee_group_constituents ADD CONSTRAINT fee_group_constituents_group_id_constituent_id_key UNIQUE (group_id, constituent_id);
ALTER TABLE ONLY public.fee_group_constituents ADD CONSTRAINT fee_group_constituents_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.fee_groups ADD CONSTRAINT fee_groups_name_key UNIQUE (name);
ALTER TABLE ONLY public.fee_groups ADD CONSTRAINT fee_groups_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.fee_structures ADD CONSTRAINT fee_structures_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.grading_scales ADD CONSTRAINT grading_scales_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.homework ADD CONSTRAINT homework_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.homework_submissions ADD CONSTRAINT homework_submissions_homework_id_student_id_key UNIQUE (homework_id, student_id);
ALTER TABLE ONLY public.homework_submissions ADD CONSTRAINT homework_submissions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.import_profiles ADD CONSTRAINT import_profiles_entity_key_name_key UNIQUE (entity_key, name);
ALTER TABLE ONLY public.import_profiles ADD CONSTRAINT import_profiles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.inventory_categories ADD CONSTRAINT inventory_categories_name_key UNIQUE (name);
ALTER TABLE ONLY public.inventory_categories ADD CONSTRAINT inventory_categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.inventory_items ADD CONSTRAINT inventory_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.inventory_items ADD CONSTRAINT inventory_items_sku_key UNIQUE (sku);
ALTER TABLE ONLY public.inventory_transactions ADD CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_invoice_no_key UNIQUE (invoice_no);
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.messages ADD CONSTRAINT messages_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.parent_contacts ADD CONSTRAINT parent_contacts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.parents ADD CONSTRAINT parents_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payments ADD CONSTRAINT payments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payroll_item_lines ADD CONSTRAINT payroll_item_lines_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payroll_items ADD CONSTRAINT payroll_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payroll_items ADD CONSTRAINT payroll_items_run_id_staff_id_key UNIQUE (run_id, staff_id);
ALTER TABLE ONLY public.payroll_run_bonus_lines ADD CONSTRAINT payroll_run_bonus_lines_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payroll_runs ADD CONSTRAINT payroll_runs_period_month_period_year_key UNIQUE (period_month, period_year);
ALTER TABLE ONLY public.payroll_runs ADD CONSTRAINT payroll_runs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.role_permissions ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.role_permissions ADD CONSTRAINT role_permissions_role_id_module_key UNIQUE (role_id, module);
ALTER TABLE ONLY public.roles ADD CONSTRAINT roles_name_key UNIQUE (name);
ALTER TABLE ONLY public.roles ADD CONSTRAINT roles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.school_settings ADD CONSTRAINT school_settings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.school_settings ADD CONSTRAINT school_settings_singleton_key UNIQUE (singleton);
ALTER TABLE ONLY public.staff_attendance ADD CONSTRAINT staff_attendance_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.staff_attendance ADD CONSTRAINT staff_attendance_staff_id_date_key UNIQUE (staff_id, date);
ALTER TABLE ONLY public.student_parents ADD CONSTRAINT student_parents_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.student_parents ADD CONSTRAINT student_parents_student_id_parent_id_key UNIQUE (student_id, parent_id);
ALTER TABLE ONLY public.students ADD CONSTRAINT students_admission_no_key UNIQUE (admission_no);
ALTER TABLE ONLY public.students ADD CONSTRAINT students_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.subjects ADD CONSTRAINT subjects_class_id_name_key UNIQUE (class_id, name);
ALTER TABLE ONLY public.subjects ADD CONSTRAINT subjects_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.teachers ADD CONSTRAINT teachers_employee_no_key UNIQUE (employee_no);
ALTER TABLE ONLY public.teachers ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.timetable_slots ADD CONSTRAINT timetable_slots_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.timetable_slots ADD CONSTRAINT timetable_unique_class_slot UNIQUE (class_id, day_of_week, period_no);
ALTER TABLE ONLY public.transport_assignments ADD CONSTRAINT transport_assignments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.transport_routes ADD CONSTRAINT transport_routes_code_key UNIQUE (code);
ALTER TABLE ONLY public.transport_routes ADD CONSTRAINT transport_routes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.transport_vehicles ADD CONSTRAINT transport_vehicles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.transport_vehicles ADD CONSTRAINT transport_vehicles_registration_no_key UNIQUE (registration_no);
ALTER TABLE ONLY public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_roles ADD CONSTRAINT user_roles_user_id_role_key UNIQUE (user_id, role);

CREATE INDEX attendance_class_date_idx ON public.attendance USING btree (class_id, date);
CREATE INDEX attendance_student_idx ON public.attendance USING btree (student_id);
CREATE INDEX events_start_date_idx ON public.events USING btree (start_date);
CREATE INDEX events_type_idx ON public.events USING btree (event_type);
CREATE INDEX exams_class_date_idx ON public.exams USING btree (class_id, exam_date DESC);
CREATE INDEX idx_admission_applications_status ON public.admission_applications USING btree (status);
CREATE INDEX idx_admission_interviews_app ON public.admission_interviews USING btree (application_id);
CREATE INDEX idx_audit_logs_created ON public.audit_logs USING btree (created_at DESC);
CREATE INDEX idx_audit_logs_entity ON public.audit_logs USING btree (entity_type, entity_id);
CREATE INDEX idx_book_issues_book ON public.book_issues USING btree (book_id);
CREATE INDEX idx_book_issues_status ON public.book_issues USING btree (status);
CREATE INDEX idx_book_issues_student ON public.book_issues USING btree (student_id);
CREATE INDEX idx_inv_items_category ON public.inventory_items USING btree (category_id);
CREATE INDEX idx_inv_txn_date ON public.inventory_transactions USING btree (txn_date);
CREATE INDEX idx_inv_txn_item ON public.inventory_transactions USING btree (item_id);
CREATE INDEX idx_messages_contact ON public.messages USING btree (parent_contact_id);
CREATE INDEX idx_notifications_created ON public.notifications USING btree (created_at DESC);
CREATE INDEX idx_notifications_status ON public.notifications USING btree (status);
CREATE INDEX idx_parent_contacts_student ON public.parent_contacts USING btree (student_id);
CREATE INDEX idx_payroll_items_run ON public.payroll_items USING btree (run_id);
CREATE INDEX idx_payroll_items_staff ON public.payroll_items USING btree (staff_id);
CREATE INDEX idx_staff_attendance_date ON public.staff_attendance USING btree (date);
CREATE INDEX idx_staff_attendance_staff ON public.staff_attendance USING btree (staff_id);
CREATE INDEX idx_student_parents_parent ON public.student_parents USING btree (parent_id);
CREATE INDEX idx_student_parents_student ON public.student_parents USING btree (student_id);
CREATE INDEX idx_subjects_class ON public.subjects USING btree (class_id);
CREATE INDEX invoices_status_idx ON public.invoices USING btree (status);
CREATE INDEX invoices_student_idx ON public.invoices USING btree (student_id);
CREATE INDEX payments_invoice_idx ON public.payments USING btree (invoice_id);
CREATE INDEX students_class_id_idx ON public.students USING btree (class_id);
CREATE INDEX students_status_idx ON public.students USING btree (status);
CREATE UNIQUE INDEX students_user_id_key ON public.students USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE UNIQUE INDEX teachers_user_id_key ON public.teachers USING btree (user_id) WHERE (user_id IS NOT NULL);
CREATE INDEX timetable_slots_class_idx ON public.timetable_slots USING btree (class_id, day_of_week, period_no);
CREATE INDEX timetable_slots_teacher_idx ON public.timetable_slots USING btree (teacher_id, day_of_week, period_no);
CREATE UNIQUE INDEX timetable_unique_teacher_slot ON public.timetable_slots USING btree (teacher_id, day_of_week, period_no) WHERE (teacher_id IS NOT NULL);
CREATE INDEX transport_assignments_route_idx ON public.transport_assignments USING btree (route_id);
CREATE UNIQUE INDEX transport_assignments_unique_active_student ON public.transport_assignments USING btree (student_id) WHERE (is_active = true);